### ISSUE TITLE
Question about table 14 in WildBench paper

### ISSUE THREAD

**Issue by xiatingyu** [allenai/wildguard#4]
Hello, I have a question regarding Table 14 in the paper. You mentioned that the Harmbench Response dataset contains 602 prompt + response pairs of data. I'd like to ask how this part of the data was obtained, because I found that only 400 pieces of data were mentioned in the Harmbench paper. If it's convenient, I wonder if you could share the way you obtained the data, or share your evaluation dataset.

**Comment by kavelrao** [comment]
Hi, please see our safety eval repository for the evaluation details: https://github.com/allenai/safety-eval
